### ISSUE TITLE
build binary run on macos error like "Bus error: 10" 

### ISSUE THREAD

**Issue by llgoer** [hroptatyr/xls2txt#2]
I clone this git repository,then run shell "make",build binary file
build run ./xls2txt -l aaa.xls, show error like "Bus error: 10"
then i download the release binary file https://github.com/hroptatyr/xls2txt/releases
it's ok,i want to know why? the makefile is not suitable for mac os system?

**Comment by hroptatyr** [comment]
Hi there,
I do not develop on MacOS.  However, I've seen there's been a lot of changes recently.  My guess would be it's a problem with the clang compiler.

This is known to work:

    $ clang --version
    Apple LLVM version 8.1.0 (clang-802.0.42)
    Target: x86_64-apple-darwin16.6.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

according to https://travis-ci.org/hroptatyr/xls2txt/builds/265824591

**Comment by llgoer** [comment]
my build environment same as :
$ clang --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

build successfull,but can't use.

**Comment by llgoer** [comment]
I build your latest version of git repository,successfull.
tks for your good job.
