### ISSUE TITLE
build error on ubuntu "undefined reference to `ceil'"

### ISSUE THREAD

**Issue by llgoer** [hroptatyr/xls2txt#3]
On ubuntu build show error "undefined reference to `ceil'"
you should change makefile like 
gcc xls2txt.o ole.o cp.o ummap.o ieee754.o -o xls2txt -lm
not 
gcc -lm xls2txt.o ole.o cp.o ummap.o ieee754.o -o xls2txt

**Comment by hroptatyr** [comment]
That depends on your make version.  The link target is built-in.
You could try defining:

    xls2txt: xls2txt.o ole.o cp.o ummap.o ieee754.o
            $(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

**Comment by llgoer** [comment]
tks
