### ISSUE TITLE
I make a project for golang binding,what's the xls2txt licence?

### ISSUE THREAD

**Issue by llgoer** [hroptatyr/xls2txt#4]
I have a golang project need xls convert to txt,then i use your code to make a golang binding.
my package url is:https://github.com/yanghuxiao/goxls2txt
and i want know your project licence.
thanks for your good job.

**Comment by hroptatyr** [comment]
GPL2+:

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    version 2 as published by the Free Software Foundation.
